services:
  kafka:
    image: confluentinc/confluent-local:7.6.0
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,EXTERNAL://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'ZjXRz-MQTz2Rk-m9v3Q_xA'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092 
    depends_on:
      - kafka

  postgres:
    image: postgres:15-alpine
    container_name: aegis-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=aegis_admin
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_DB=aegis_threats
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro,z

  ingestion-api:
    build:
      context: ../services/ingestion-api
      dockerfile: Dockerfile
    container_name: ingestion-api
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=raw-threat-intel
    depends_on:
      - kafka

  analyzer-worker:
    build:
      context: ../services/analyzer-worker
      dockerfile: Dockerfile
    container_name: analyzer-worker
    env_file:
      - ../services/analyzer-worker/.env
    environment:
      - KAFKA_BROKER=kafka:29092
      - KAFKA_TOPIC=raw-threat-intel
      - KAFKA_CONSUMER_GROUP=analyzer-worker-group
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=aegis_threats
      - POSTGRES_USER=aegis_admin
      - POSTGRES_PASSWORD=supersecretpassword
    depends_on:
      - kafka
      - postgres

volumes:
  pg_data: